### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by thedrayman** [MasterMarci/settlers#2]
Hey, hast du Langeweile oder willst du hier wieder etwas machen?
Wie geht's dir so?

Gruß!

**Comment by MasterMarci** [comment]
Hab nur den Github-Security Alert aufgelöst. Da die JUnit Version wohl eine Sicherheitslücke enthielt. 
habe gerade ein bisschen Zeit an der Hand also mache ich vielleicht die Woche noch was, habe mir aber aktuell nichts fest vorgenommen.

**Comment by thedrayman** [comment]
Ah sehr gut! 
Bin gespannt! ;)
